#!/usr/bin/env python3
"""Scan a reference tree and write an exact-duplicate review report.

The tool never deletes or moves files. It hashes files with SHA-256 and groups
identical content, then highlights likely documentation duplicates while
separating repeated vendor/build templates that usually belong to different
example snapshots.
"""

from __future__ import annotations

import argparse
import hashlib
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKIP_PARTS = {".git", ".claude", ".codex", "Debug", "Objects", "Listings"}
DOC_SUFFIXES = {
    ".pdf", ".txt", ".md", ".rst", ".html", ".htm", ".doc", ".docx",
    ".ppt", ".pptx", ".xls", ".xlsx", ".csv", ".json", ".syscfg",
    ".c", ".h", ".cpp", ".py", ".ino", ".zip", ".7z", ".png", ".jpg",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def is_template_duplicate(paths: list[Path]) -> bool:
    text = " ".join(path.as_posix().lower() for path in paths)
    return (
        "source/ti/" in text
        or "source/third_party" in text
        or ".meta/" in text
        or "keil/" in text
        or "project outputs" in text
        or "tianmengxing/examples" in text
        and any(path.name.lower() in {"readme.md", "readme.txt", "mspm0g3507.sct", "startup_mspm0g350x_uvision.s"} for path in paths)
    )


def scan(root: Path) -> tuple[int, dict[str, list[Path]]]:
    groups: dict[str, list[Path]] = defaultdict(list)
    files = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file() or any(part in SKIP_PARTS for part in path.parts):
            continue
        try:
            digest = sha256(path)
        except OSError:
            continue
        groups[digest].append(path)
        files += 1
    return files, groups


def write_report(root: Path, output: Path) -> None:
    files, groups = scan(root)
    duplicate_groups = [paths for paths in groups.values() if len(paths) > 1]
    candidate_groups = [
        paths
        for paths in duplicate_groups
        if any(path.suffix.lower() in DOC_SUFFIXES for path in paths)
        and not is_template_duplicate(paths)
    ]
    sensor_candidates = [
        paths
        for paths in candidate_groups
        if any("sensors" in path.parts for path in paths)
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        root_display = root.relative_to(ROOT).as_posix()
    except ValueError:
        root_display = root.as_posix()
    lines = [
        "# Reference duplicate review",
        "",
        "> Generated by `tools/find_duplicate_docs.py`. This report is evidence for manual review; it never deletes or moves files.",
        "",
        f"- Scan root: `{root_display}`",
        f"- Files scanned: `{files}`",
        f"- Exact duplicate groups: `{len(duplicate_groups)}`",
        f"- Candidate documentation groups after template filtering: `{len(candidate_groups)}`",
        f"- Sensor-focused candidate groups: `{len(sensor_candidates)}`",
        "",
        "## Review rules",
        "",
        "1. Keep one canonical raw manual or datasheet and its provenance record.",
        "2. Keep extracted text only when it has a matching source hash and is searchable.",
        "3. Keep runnable examples only when their board/toolchain context is distinct.",
        "4. Move a suspected duplicate to `99_quarantine/` before deleting it; update indexes and commit the review separately.",
        "5. Re-run the scanner after every cleanup pass.",
        "",
        "## High-confidence sensor/document candidates",
        "",
    ]
    if not sensor_candidates:
        lines.append("No sensor candidates found.")
    else:
        for index, paths in enumerate(sorted(sensor_candidates, key=lambda group: [p.as_posix() for p in group]), 1):
            digest = next(key for key, value in groups.items() if value is paths)
            lines.append(f"### Candidate {index} — identical SHA-256 `{digest}`")
            for path in paths:
                lines.append(f"- `{path.relative_to(ROOT).as_posix()}`")
            lines.append("")
    lines.extend([
        "## Known high-confidence actions",
        "",
        "- The duplicate NCHD1 manual PDF and extracted-text filename have been removed; the ASCII-named canonical pair remains.",
        "- The NCHD12 MSPM0G3507 example under `sensors/NCHD1_I2C/` duplicates the filtered snapshot under `sensors/examples/nchd12_mspm0g3507/` for many source/configuration files. Keep the filtered searchable snapshot as the canonical example and review the larger archive before deletion.",
        "- Repeated Tianmengxing example startup files, linker scripts, and README templates are usually intentional per-example snapshots; do not delete them solely because their hashes match.",
        "- LP-MSPM0G3507 ODB/manufacturing outputs contain many repeated generated files; treat each production package as a unit and do not delete individual files from it.",
        "",
        "## Template/build duplicate count",
        "",
        f"- Exact groups classified as repeated templates or generated/vendor support: `{len(duplicate_groups) - len(candidate_groups)}`.",
        "- These are reported for awareness but are not deletion candidates without checking the owning example or production package.",
        "- Deleted documentation copies are recorded in `docs/logs/DUPLICATE_CLEANUP_20261007.md`.",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"scanned={files} exact_groups={len(duplicate_groups)} candidates={len(candidate_groups)}")
    print(output.as_posix())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("docs/reference"))
    parser.add_argument("--output", type=Path, default=Path("docs/reference/DOCUMENT_DUPLICATES.md"))
    args = parser.parse_args()
    root = (ROOT / args.root).resolve() if not args.root.is_absolute() else args.root
    output = (ROOT / args.output).resolve() if not args.output.is_absolute() else args.output
    if not root.is_dir():
        parser.error(f"scan root does not exist: {root}")
    write_report(root, output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
